import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.scss";
import "./app.styles.scss";
import GoogleAnalytics from "./components/GoogleAnalytics/GoogleAnalytics";
import { AppProvider } from "./context/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Agilizai App",
  description: "Generated by agilizai app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <GoogleAnalytics />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
